name: Build & Test

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
    - name: Set env
      run: |
          echo "KONG_SOURCE_LOCATION=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "KONG_BUILD_TOOLS_LOCATION=$HOME/kong-build-tools" >> $GITHUB_ENV
          echo "DOCKER_REPOSITORY=ghcr.io/hutchic-org/kong" >> $GITHUB_ENV

    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GCR_USERNAME }}
        password: ${{ secrets.GCR_TOKEN }}

    - name: Checkout Kong source code
      uses: actions/checkout@v2

    - name: Setup Kong Build Tools
      run: make setup-kong-build-tools

    - name: Build Test Image
      run: pushd $KONG_BUILD_TOOLS_LOCATION && make kong-test-container && popd

  lint-doc-and-unit-tests:
    name: Lint, Doc and Unit tests
    runs-on: ubuntu-20.04
    needs: build

    env:
      TEST_SUITE: unit

    steps:
    - name: Set env
      run: |
          echo "KONG_SOURCE_LOCATION=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "KONG_BUILD_TOOLS_LOCATION=$HOME/kong-build-tools" >> $GITHUB_ENV
          echo "DOCKER_REPOSITORY=ghcr.io/hutchic-org/kong" >> $GITHUB_ENV

    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GCR_USERNAME }}
        password: ${{ secrets.GCR_TOKEN }}

    - name: Checkout Kong source code
      uses: actions/checkout@v2

    - name: Setup Kong Build Tools
      run: make setup-kong-build-tools

    - name: Run Tests
      run: pushd $KONG_BUILD_TOOLS_LOCATION && make test-kong && popd

  pdk:
    name: PDK
    runs-on: ubuntu-18.04
    needs: build

    env:
      TEST_SUITE: pdk
      DEBUG: 1

    steps:
    - name: Set env
      run: |
          echo "KONG_SOURCE_LOCATION=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "KONG_BUILD_TOOLS_LOCATION=$HOME/kong-build-tools" >> $GITHUB_ENV
          echo "DOCKER_REPOSITORY=ghcr.io/hutchic-org/kong" >> $GITHUB_ENV

    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GCR_USERNAME }}
        password: ${{ secrets.GCR_TOKEN }}

    - name: Checkout Kong source code
      uses: actions/checkout@v2

    - name: Setup Kong Build Tools
      run: make setup-kong-build-tools

    - name: Run Tests
      run: pushd $KONG_BUILD_TOOLS_LOCATION && make test-kong && popd

  package-and-smoke-test:
    name: Package and smoke test Kong
    runs-on: ubuntu-18.04
    needs: build

    steps:
    - name: Set env
      run: |
          echo "KONG_SOURCE_LOCATION=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "KONG_BUILD_TOOLS_LOCATION=$HOME/kong-build-tools" >> $GITHUB_ENV
          echo "DOCKER_REPOSITORY=ghcr.io/hutchic-org/kong" >> $GITHUB_ENV

    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GCR_USERNAME }}
        password: ${{ secrets.GCR_TOKEN }}

    - name: Checkout Kong source code
      uses: actions/checkout@v2

    - name: Setup Kong Build Tools
      run: make setup-kong-build-tools

    - name: Package Kong
      run: pushd $HOME/kong-build-tools && make package-kong

    - name: Smoke Test Kong
      run: pushd $HOME/kong-build-tools && make test

  integration-tests-dbless:
    name: DB-less integration tests
    runs-on: ubuntu-18.04
    needs: build

    env:
      TEST_DATABASE: 'off'
      TEST_SUITE: dbless

    steps:
    - name: Set env
      run: |
          echo "KONG_SOURCE_LOCATION=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "KONG_BUILD_TOOLS_LOCATION=$HOME/kong-build-tools" >> $GITHUB_ENV
          echo "DOCKER_REPOSITORY=ghcr.io/hutchic-org/kong" >> $GITHUB_ENV

    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GCR_USERNAME }}
        password: ${{ secrets.GCR_TOKEN }}

    - name: Checkout Kong source code
      uses: actions/checkout@v2

    - name: Setup Kong Build Tools
      run: make setup-kong-build-tools

    - name: Run Tests
      run: pushd $KONG_BUILD_TOOLS_LOCATION && make test-kong && popd

  integration-tests-cassandra:
    name: C* ${{ matrix.cassandra_version }} ${{ matrix.suite }} - ${{ matrix.split }} tests
    runs-on: ubuntu-20.04
    needs: build
    
    strategy:
      matrix:
        suite: [integration, plugins]
        cassandra_version: [3]
        split: [all, first (01-04), second (>= 05)]
        exclude:
          - suite: plugins
            split: first (01-04)
          - suite: plugins
            split: second (>= 05)
          - suite: integration
            split: all

    env:
      TEST_DATABASE: cassandra
      TEST_SUITE: ${{ matrix.suite }}
      TEST_SPLIT: ${{ matrix.split }}

    steps:
    - name: Set env
      run: |
          echo "KONG_SOURCE_LOCATION=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "KONG_BUILD_TOOLS_LOCATION=$HOME/kong-build-tools" >> $GITHUB_ENV
          echo "DOCKER_REPOSITORY=ghcr.io/hutchic-org/kong" >> $GITHUB_ENV

    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GCR_USERNAME }}
        password: ${{ secrets.GCR_TOKEN }}

    - name: Checkout Kong source code
      uses: actions/checkout@v2

    - name: Setup Kong Build Tools
      run: make setup-kong-build-tools

    - name: Run Tests
      run: pushd $KONG_BUILD_TOOLS_LOCATION && make test-kong && popd

  integration-tests-postgres:
    name: Postgres ${{ matrix.suite }} - ${{ matrix.split }} tests
    runs-on: ubuntu-20.04
    needs: build
    
    strategy:
      matrix:
        suite: [integration, plugins]
        split: [all, first (01-04), second (>= 05)]
        exclude:
          - suite: plugins
            split: first (01-04)
          - suite: plugins
            split: second (>= 05)
          - suite: integration
            split: all

    env:
      TEST_DATABASE: postgres
      TEST_SUITE: ${{ matrix.suite }}
      TEST_SPLIT: ${{ matrix.split }}

    steps:
    - name: Set env
      run: |
          echo "KONG_SOURCE_LOCATION=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "KONG_BUILD_TOOLS_LOCATION=$HOME/kong-build-tools" >> $GITHUB_ENV
          echo "DOCKER_REPOSITORY=ghcr.io/hutchic-org/kong" >> $GITHUB_ENV

    - name: Login to GCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GCR_USERNAME }}
        password: ${{ secrets.GCR_TOKEN }}

    - name: Checkout Kong source code
      uses: actions/checkout@v2

    - name: Setup Kong Build Tools
      run: make setup-kong-build-tools

    - name: Run Tests
      run: pushd $KONG_BUILD_TOOLS_LOCATION && make test-kong && popd